apiVersion: v1
kind: ConfigMap

metadata:
  name: today-api-config

data:
  database-url: "postgres://postgres:postgres@postgres:5432/today"
  jwt-secret: "superduper-very-secret"
  jwt-expiration: "64800"
  jwt-audience: "mattiejas.sh"
  jwt-issuer: "mattiejas.sh"
