apiVersion: apps/v1
kind: Deployment
metadata:
   name: today-api
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
        app: api
   template:
      metadata:
         labels:
           app: api
      spec:
         containers:
            - name: api 
              image: mattiejas/today-api 
              env:
                - name: DATABASE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: api-config
                      key: database-url
                - name: JWT_SECRET
                  valueFrom:
                    configMapKeyRef:
                      name: api-config
                      key: jwt-secret
                - name: JWT_AUDIENCE
                  valueFrom:
                    configMapKeyRef:
                      name: api-config
                      key: jwt-audience
                - name: JWT_EXPIRATION
                  valueFrom:
                    configMapKeyRef:
                      name: api-config
                      key: jwt-expiration
                - name: JWT_ISSUER
                  valueFrom:
                    configMapKeyRef:
                      name: api-config
                      key: jwt-issuer
---
apiVersion: v1
kind: Service
metadata:
   name: today-api-service 
   namespace: default
spec:
   type: NodePort
   selector:
     app: api
   ports:
      - port: 3001
        targetPort: 3001
        nodePort: 30001
        protocol: TCP
