apiVersion: apps/v1
kind: Deployment
metadata:
  name: today-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: today-api
  template:
    metadata:
      labels:
        app: today-api
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: today-api
          image: mattiejas/today-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: today-api-config
                  key: database-url
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: today-api-config
                  key: jwt-secret
            - name: JWT_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: today-api-config
                  key: jwt-audience
            - name: JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: today-api-config
                  key: jwt-expiration
            - name: JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: today-api-config
                  key: jwt-issuer
---
apiVersion: v1
kind: Service
metadata:
  name: today-api-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: today-api
  ports:
    - port: 5000
      targetPort: 3001
