apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: today-ui-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`mattiejas.sh`)
      kind: Rule
      services:
        - kind: Service
          name: today-ui-service
          port: 4000

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: today-ui-ingress-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mattiejas.sh`)
      kind: Rule
      services:
        - kind: Service
          name: today-ui-service
          port: 4000
  tls:
    certResolver: "mattiejasresolver"
    domains:
      - main: "mattiejas.sh"