###

GET http://[::1]:3001/health

###

POST http://[::1]:3001/auth/register
Content-Type: application/json

{
    "username": "test",
    "email": "test@example.com",
    "password": "test"
}

### 

POST http://[::1]:3001/auth/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}


###

GET http://[::1]:3001/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2Njc1YzQwNi04YzBkLTQyZWItOTJmYi0zNTk3ODRjMDc2ZTQiLCJhdWQiOiJhdWRpZW5jZSIsImlzcyI6ImF1ZGllbmNlIiwiZXhwIjoxNzA2MzU0NjM0LCJuYW1lIjoidGVzdCIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSJ9.qalkHqPxOPc9YO3F0pLr7ffqWASwY4p1eb4zjXC0VwY 