###

GET http://[::1]:3001/health

###

POST http://[::1]:3001/auth/register
Content-Type: application/json

{
    "username": "test",
    "email": "test@example.com",
    "password": "test"
}

### 

POST http://[::1]:3001/auth/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "test"
}